---
title: "ML2-Assignment2"
author: "GroupA"
date: "10/7/2019"
output: html_document
---

## Load Data

```{r load libraries and datasets, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Metrics)
library(readr)
library(ggplot2)
library(e1071)     
library(glmnet)    
library(caret)     
library(FSelector) 
library(dplyr)
library(stats)
library(purrr)
library(tidyr)
library(questionr)
library(doMC)
library(maptree)
library(corrplot)
library(data.table)
library(scales)
library(MASS)
library(rpart)
library(rpart.plot)

test_values = read.csv(file = file.path('Pump_it_Up_Data_Mining_the_Water_Table_-_Test_set_values.csv'),  header = TRUE, dec = ".", sep = ",")
train_values = read.csv(file = file.path('Pump_it_Up_Data_Mining_the_Water_Table_-_Training_set_values.csv'),  header = TRUE, dec = ".", sep = ",")
train_labels = read.csv(file = file.path('Pump_it_Up_Data_Mining_the_Water_Table_-_Training_set_labels.csv'),  header = TRUE, dec = ".", sep = ",")
test_labels = read.csv(file = file.path('Pump_it_Up_Data_Mining_the_Water_Table_-_Submission_format.csv'),  header = TRUE, dec = ".", sep = ",")

```


```{r cars} 
# este codigo sale en el markdown

str(train_values)
summary(train_values)
head(train_values)
dim(train_values) # 180x14
class(train_values) # data.frame

# combine datasets
training <- left_join(train_values, train_labels) # joining by id
testing <- left_join(test_values, test_labels) # joining by id

# join train and test values to do transformations
df <- rbind(training, testing)
df <- df[,-1] # remove the ID for the exercise and we will include it at the end
# training: [,1:59400]
# testing: [,59401:74250]
```



```{r pressure, echo=FALSE}
#con echo = FALSE el codigo no sale en el markdown

missing <- sapply(df, function(x){sum(is.na(x))})
missing[order(missing, decreasing = TRUE)] # there are no missing values

```

```{r}
# see number of unique values per feature
unique_values<- function(x){
return(length(unique(x)));
}
unique <- sapply(df, unique_values)
unique[order(unique)]

# recorded_by is constant
```

